export const STOPWORDS = new Set([
  'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'her', 'was',
  'one', 'our', 'out', 'day', 'get', 'has', 'him', 'his', 'how', 'man', 'new',
  'now', 'old', 'see', 'two', 'way', 'who', 'boy', 'did', 'its', 'let', 'put',
  'say', 'she', 'too', 'use', 'this', 'that', 'with', 'have', 'from', 'they',
  'will', 'would', 'there', 'their', 'what', 'about', 'which', 'when', 'make',
  'like', 'time', 'just', 'know', 'take', 'people', 'into', 'year', 'your',
  'good', 'some', 'could', 'them', 'than', 'then', 'look', 'only', 'come',
  'over', 'think', 'also', 'back', 'after', 'work', 'first', 'well', 'even',
  'want', 'because', 'these', 'give', 'most', 'app', 'apps', 'application',
  'really', 'much', 'very', 'still', 'been', 'being', 'were', 'had', 'has',
  'does', 'doing', 'done', 'any', 'each', 'few', 'more', 'other', 'such',
  'own', 'same', 'here', 'why', 'once', 'again', 'both', 'itself', 'ourselves',
  'yourself', 'himself', 'herself', 'themselves', 'until', 'while', 'off',
  'down', 'under', 'further', 'once', 'nor', 'ain', 'aren', 'couldn', 'didn',
  'doesn', 'hadn', 'hasn', 'haven', 'isn', 'shan', 'shouldn', 'wasn', 'weren',
  'won', 'wouldn', 'don', 'should', 'can', 'will', 'just', 'now', 'i', 'me',
  'my', 'myself', 'we', 'our', 'ours', 'you', 'youre', 'youve', 'youll',
  'youd', 'yours', 'he', 'him', 'his', 'she', 'shes', 'it', 'its', 'they',
  'them', 'their', 'a', 'an', 'in', 'on', 'at', 'to', 'of', 'is', 'be', 'or',
  'if', 'as', 'so', 'no', 'do',
]);
